services:
  api:
    ports:
      - 3553:3553
    volumes:
      - ./API:/app/api
  chatbot:
    ports:
      - 3550:3550
    volumes:
      - ./ChatBot:/app/chatbot
    links:
      - api
    depends_on:
      - api
