services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile.dev
    ports:
      - 3553:3553
    volumes:
      - ./API/src:/app/api/src
  chatbot:
    env_file:
      - ./.env
    build:
      context: ./ChatBot
      dockerfile: Dockerfile.dev
    ports:
      - 3550:3550
    volumes:
      - ./ChatBot:/app/chatbot
